### ISSUE TITLE
크래시 디버깅 경험

### ISSUE THREAD

**Issue by lminsu** [lminsu/MovieTrailer#25]
### 프래그먼트에 생성자 인자를 추가하면 가로모드 회전 시 에러 발생
- 이슈 발생 코드
  - MainFragment 클래스에 생성자 파라미터를 추가함
    - <img width=400 src="https://github.com/user-attachments/assets/85603589-6898-4cca-b7e5-14446e05b06f" />
  - 뷰페이저어댑터 createFragment 콜백에서 MainFragment를 생성할 떄 생성자 파라미터를 넘겨주면서 생성
    - <img width=400 src="https://github.com/user-attachments/assets/bbca0c4c-ffa9-4aa2-9b22-9c8e1d0cf50a" />
- 이슈 발생 시나리오
  - 가로모드 회전 시 크래시 발생

![image](https://github.com/user-attachments/assets/e4ef2f55-d225-4d63-ac31-3f546ba8f04b)

```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.movietrailer/com.example.movietrailer.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.movietrailer.ui.main.MainFragment: could not find Fragment constructor
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
  at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5802)
  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5710)
  at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
  at android.os.Handler.dispatchMessage(Handler.java:107)
  at android.os.Looper.loop(Looper.java:237)
  at android.app.ActivityThread.main(ActivityThread.java:8167)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
 Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.movietrailer.ui.main.MainFragment: could not find Fragment constructor
  at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
  at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
  at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
  at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
  at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
  at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1890)
  at androidx.fragment.app.Fragment.onCreate(Fragment.java:1867)
  at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
  at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
  at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
  at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
  at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
  at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
  at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
  at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
  at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
  at com.example.movietrailer.MainActivity.onCreate(MainActivity.kt:10)
  at android.app.Activity.performCreate(Activity.java:7963)
  at android.app.Activity.performCreate(Activity.java:7952)
  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
  at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5802) 
  at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5710) 
  at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
  at android.os.Handler.dispatchMessage(Handler.java:107) 
  at android.os.Looper.loop(Looper.java:237) 
  at android.app.ActivityThread.main(ActivityThread.java:8167) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
```
- 에러 메시지
  - java.lang.RuntimeException: **Unable to start activity** ComponentInfo{`com.example.movietrailer/com.example.movietrailer.MainActivity`}: ⚠️**Unable to instantiate fragment** `com.example.movietrailer.ui.main.MainFragment`: ⚠️**could not find Fragment constructor**
  - Activity를 생성하려고 하는데 Fragment의 생성자를 찾을 수 없다고 함
- 관련 코드
  - `performLaunchActivity()` 함수 내부 catch 문에서 Exception 발생시킴
    - <img width=500 src="https://github.com/user-attachments/assets/1b3ec3b9-a16e-4349-88aa-30e8cdb6b671" />
    - <img width=350 src="https://github.com/user-attachments/assets/19d05d97-ab46-48af-932f-fe2a53e71bfc" />
  - `performLaunchActivity()` 함수 내부 try~catch 문에서 에러가 발생하여 catch 문을 타는데, 이때 if 문에 걸려 Exception을 throw 함
  - → throw할 때 catch로 들어온 Exception의 에러 메시지를 같이 보여줌
    - <img width=700 src="https://github.com/user-attachments/assets/35f61bd8-d718-4a8d-9b17-ad8308f213f5" />
  - → e.toString()에 있는 내용이 더 근본적인 원인! 
    - **Unable to instantiate fragment** `com.example.movietrailer.ui.main.MainFragment`: **could not find Fragment constructor**
  - → Fragment 생성자를 찾을 수 없어서 프래그먼트를 생성할 수 없다고 함
- 가로모드 회전을 하면 Activity를 재생성하면서 Fragment도 재생성하는데, 이때 안드로이드 내부 코드에서 항상 기본 생성자를 이용하여 Fragment를 생성하려고함
  - → MovieFragment에 생성자 파라미터를 추가하면, 기본 생성자는 없어짐, 생성자 파라미터 있는 생성자 밖에 안 남음
  - → MovieFragment에 기본 생성자가 없는데, 안드로이드 내부 코드에서 기본 생성자로 생성하려고 하니 없는 메소드여서 에러 발생
- 해결
  - 필요한 생성자 인자는 Fragment.arguments에 저장하여 사용(이후 onCreate()에서 arguments에 저장된 값 꺼내서 사용함)
    - 재생성 때도 arguments에 저장되어 있는 값들은 사라지지 않고 남아 있음
  - [참고 링크](https://developer.android.com/reference/android/app/Fragment#Fragment())
    - ![image](https://github.com/user-attachments/assets/59ac0d1b-37f3-418c-9f34-dcb4d76aa204)
  - 관련 코드
    - 프래그먼트 생성할 때, arugments에 필요한 정보를 담아서 프래그먼트를 생성하는 함수 추가
      - <img width=300 src="https://github.com/user-attachments/assets/fe1febd1-9094-4cb6-b660-8fae83153872" />
    - 프래그먼트 생성 시 해당 함수 사용
      - <img width=300 src="https://github.com/user-attachments/assets/e15177bc-59bc-45a5-b3b2-9c386e790cea" />
    - 프래그먼트 onCreate() 떄 arguements에 저장된 값 꺼내서 사용
      - <img width=300 src="https://github.com/user-attachments/assets/9ed47792-27f1-4087-826d-6fcad4e0721d" />
- 특이사항
  - arguments는 Bundle 타입이며, 저장하고 싶은 값을 바로 저장하는 것이 아니라 Bundle 인스턴스에 저장하는 식으로 사용함

**Comment by lminsu** [comment]
### 뷰모델 생성 시점을 프래그먼트 생성 시점과 동일하게 하면 크래시 발생
- 이슈 발생 코드
  - 프래그먼트 init 시점에 뷰모델을 생성하도록 함
  - <img width=400 src="https://github.com/user-attachments/assets/f9dd5aa5-2d2a-42ed-b1fe-8331e4446ef0" />
- 이슈 발생 시나리오
  - 앱 실행

<img src="https://github.com/user-attachments/assets/4dd0c212-6bbf-4369-ba37-82d8a706fc9f" />

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.movietrailer/com.example.movietrailer.MainActivity}: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
 	at android.os.Handler.dispatchMessage(Handler.java:107)
 	at android.os.Looper.loop(Looper.java:237)
 	at android.app.ActivityThread.main(ActivityThread.java:8167)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.IllegalStateException: Can't access ViewModels from detached fragment
 	at androidx.fragment.app.Fragment.getViewModelStore(Fragment.java:398)
 	at androidx.lifecycle.ViewModelProvider.<init>(ViewModelProvider.kt:127)
 	at com.example.movietrailer.ui.pager.PagerFragment.makePagerViewModel(PagerFragment.kt:105)
 	at com.example.movietrailer.ui.pager.PagerFragment.<init>(PagerFragment.kt:27)
 	at com.example.movietrailer.MainActivity.onCreate(MainActivity.kt:17)
 	at android.app.Activity.performCreate(Activity.java:7963)
 	at android.app.Activity.performCreate(Activity.java:7952)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
 	at android.os.Handler.dispatchMessage(Handler.java:107) 
 	at android.os.Looper.loop(Looper.java:237) 
 	at android.app.ActivityThread.main(ActivityThread.java:8167) 
 	at java.lang.reflect.Method.invoke(Native Method) 
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100) 
 	...
```
- 에러 메시지
  - java.lang.IllegalStateException: ⚠️**Can't access ViewModels from detached fragment**
  - detach된 프래그먼트에서는 뷰모델을 접근할 수 없다고 함
- 관련 코드
  - Fragment init 시점에 PagerViewModel 생성하는 함수 호출
    - <img width=450 src="https://github.com/user-attachments/assets/fe4b88b2-7e6d-40a4-bd36-e3c386a060a5" />
  - makePagerViewModel() 함수 내부에서 ViewModelProvider 생성하는 코드 있음
    - <img width=550 src="https://github.com/user-attachments/assets/21c4282b-be38-4acd-8701-dccc6d690eb7" />
  - ViewModelProvider 생성할 떄 호출한 생성자를 보니 owner의 viewModelStore에 접근하는 코드 있음(여기서 owner는 Fragment임)
    - <img width=500 src="https://github.com/user-attachments/assets/1fa071a4-bd28-4608-b638-065f6bbd289e" />
  - Fragment.getViewModelStore 내부에서 mFragmentManager가 null이면 에러 발생시킴
    - (참고) owner.viewModelStore와 Fragment.getViewModelStore()는 동일한 코드임 - 해당 kotlin 코드에 대응되는 자바 코드
    - <img width=600 src="https://github.com/user-attachments/assets/feaee1a5-d263-472c-9bb8-0589788a4429" />
- 프래그먼트 생성 → 프로퍼티들을 init → 뷰모델을 생성 → 뷰모델프로바이더 생성 → 뷰모델프로바이더 생성자 코드에서 Fragment.getViewModelStore() 호출 → 해당 함수 내부 if 문에 걸려 에러 발생
- 해결
  - viewModel 프로퍼티를 by lazy로 정의하여 뷰모델 생성 시점을 onAttach 이후로 옮김
    - 어떤 프로퍼티를 by lazy로 정의하면, 해당 프로퍼티를 처음 사용할 때 by lazy 코드가 수행됨
  - onStart() 이후 by lazy 코드가 호출되는 것 확인
    - <img width=330 src="https://github.com/user-attachments/assets/bd0e8511-45fc-4bd5-b01a-3f5bc2c62d20" />
